<div class="clearfix-120"></div>
<div id="content-wrapper" class="container">
	<section id="intro-main" class="row">
		<ul id="intro-slide-1" class="slide">
			<li>that awkward moment</li>
			<li>when the code you wrote two months ago</li>
			<li>makes no sense whatsoever</li>
		</ul>
		<ul id="intro-slide-2" class="slide">
			<li>our dev team</li>
			<li>just hired a new person</li>
			<li>now what</li>
		</ul>
		<ul id="intro-slide-3" class="slide">
			<li>my dev team uses a wiki</li>
			<li>for instruction, data and documentation</li>
			<li>...ugh</li>
		</ul>
		<ul id="intro-slide-4" class="slide">
			<li class="twocol"><img src="images/landing/define.png" alt="define" /></li>
			<li class="fivecol"><img src="images/landing/document.png" alt="document" /></li>
			<li class="twocol last"><img src="images/landing/develop.png" alt="develop" /></li>
		</ul>
	</section>
</div>
<div class="clearfix-120"></div>
<div class="container">
	<section id="intro-signup" class="row">
		<ul id="signup" class="landing-list">
			<li><img src="images/landing/coming-soon.png" alt="coming soon!" /></li>
			<li><img src="images/landing/else.png" alt="coming soon!"</li>
			<ul id="signup-form-wrapper">
				<li>
					<form id="signup-form" method="post">
						<input type="text" id="signup-input" name="signup-input" class="DD-form-input email" value="email address"><br />
						<input type="submit" value="tell me when!" name="email-submit">
					</form>
				</li>
			</ul>
		</ul>
	</section>
	<section id="intro-thank-you" class="row">
		<ul id="thank-you" class="landing-list">
			<li><img src="images/landing/word.png" alt="Word!" /></li>
			<div class="clearfix-50"></div>
			<li>Thanks for showing interest!</li>
			<li>We'll send you updates and all that jazz as our application develops!</li>
		</ul>
	</section>
</div>